CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.5 --width_mult 0.25

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.5 --width_mult 0.5

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.5 --width_mult 0.75

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.5 --width_mult 1.0

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.75 --width_mult 0.25

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.75 --width_mult 0.5

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.75 --width_mult 0.75

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 0.75 --width_mult 1.0

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 1.0 --width_mult 0.25

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 1.0 --width_mult 0.5

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 1.0 --width_mult 0.75

CUDA_VISIBLE_DEVICES=7 python eval_glue.py  --model_type bert --task_name SST-2 --data_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/glue/SST-2 --max_seq_length 128 --model_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert/SST-2/bert/ --output_dir /nethome/sannavajjala6/projects/Pretrained-Language-Model/DynaBERT/dynabert_outputs/SST-2 --depth_mult 1.0 --width_mult 1.0
